# Dependencies
markdown:         kramdown
highlighter:      rogue

kramdown:
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Bug Repellent
tagline:          The blog of @captainsafia
url:              https://blog.safia.rocks
baseurl:          /

author:
  name:           'Safia Abdalla'
  url:            https://github.com/captainsafia

plugins:
  - jekyll-feed
  - jekyll-mermaid
  - jekyll-target-blank
  - jekyll-seo-tag
  - jekyll-og-image
  - jemoji
  - jekyll-sitemap

mermaid:
  src: https://cdn.jsdelivr.net/npm/mermaid@10.9.1/dist/mermaid.min.js

# Custom vars
urls:
  about:          https://safia.rocks
  github:         https://github.com/captainsafia

defaults:
  - scope:
      path: ""        # site-wide
      type: posts     # NOT "post" or "pages"
    values:
      layout: post
  - scope:
      path: "assets/images"
    values:
      image: true

og_image:
  collections: ["posts", "pages"]
  output_dir: "assets/images/og"
  domain: "blog.safia.rocks"
  border_bottom:
    width: 20
    fill:
      - "#6b8e3f"

# Do not publish future posts
future: false